services:
  mysql_db:
    image: mysql:5.6.41
    container_name: sql_injection_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sql_inject_test
      MYSQL_USER: naufalyafi
      MYSQL_PASSWORD: pwd27112024accessadmindb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  php_server:
    build: ./php
    container_name: sql_injection_php
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - mysql_db
